### ISSUE TITLE
App Suggestion: Twire

### ISSUE THREAD

**Issue by RickyM7** [albertomosconi/foss-apps#13]
### App Name
Twire

### Description
An Open Source, AD-Free Twitch browser and stream player for Android. Supports VODs with chat replay, custom emotes (BTTV and FFZ) and Picture in Picture mode. A fork of Pocket Plays for Twitch.

### Category
Entertainment

### Links
Source: https://github.com/twireapp/Twire
F-Droid: https://f-droid.org/packages/com.perflyst.twire

**Comment by albertomosconi** [comment]
Added, thanks for your submission
