### ISSUE TITLE
App Suggestion: Music Player GO

### ISSUE THREAD

**Issue by RickyM7** [albertomosconi/foss-apps#14]
### App Name
Music Player GO

### Description
A simple yet fully-featured local music player aiming at simplicity and performance.

### Category
Media Players

### Links
Source: https://github.com/enricocid/Music-Player-GO
F-Droid: https://f-droid.org/packages/com.iven.musicplayergo
Play Store: https://play.google.com/store/apps/details?id=com.iven.musicplayergo

**Comment by albertomosconi** [comment]
Added, thanks for the submission.
