### ISSUE TITLE
App Suggestion: Tachiyomi

### ISSUE THREAD

**Issue by RickyM7** [albertomosconi/foss-apps#17]
### App Name
Tachiyomi

### Description
A Free and Open Source manga reader for Android.

### Category
Entertainment

### Links
Source: https://github.com/inorichi/tachiyomi
F-Droid: https://f-droid.org/en/packages/eu.kanade.tachiyomi
Website: https://tachiyomi.org

**Comment by albertomosconi** [comment]
Thanks, I'll add it now
