### ISSUE TITLE
App Suggestion: Librera Reader PRO

### ISSUE THREAD

**Issue by RickyM7** [albertomosconi/foss-apps#18]
### App Name
Librera Reader PRO

### Description
An e-book reader for Android devices; it supports the following formats: PDF, EPUB, EPUB3, MOBI, DjVu, FB2, TXT, RTF, AZW, AZW3, HTML, CBZ, CBR, DOC, DOCX, and OPDS Catalogs.

### Category
Document & PDF Viewer

Note: Please add this category, it encompasses all apps related to text editing and ebook reading.

### Links
Source: https://github.com/foobnix/LibreraReader
F-Droid: https://f-droid.org/en/packages/com.foobnix.pro.pdf.reader
Play Store: https://play.google.com/store/apps/details?id=com.foobnix.pro.pdf.reader
Website: http://librera.mobi

**Comment by albertomosconi** [comment]
For now I've added it to Media Players, I plan in the future to create subcategories like Images, Music and PDFs so this will be sorted accordingly. Thanks for the suggestion!
