### ISSUE TITLE
App Suggestion: Download Navi

### ISSUE THREAD

**Issue by RickyM7** [albertomosconi/foss-apps#19]
### App Name
Download Navi

### Description
A Free and Open Source software download manager.

### Category
Utilities

### Links
Source: https://github.com/TachibanaGeneralLaboratories/download-navi
F-Droid: https://f-droid.org/en/packages/com.tachibana.downloader
Play Store: https://play.google.com/store/apps/details?id=com.tachibana.downloader

**Comment by albertomosconi** [comment]
Thanks!
