### ISSUE TITLE
App Suggestion: MoeList

### ISSUE THREAD

**Issue by RickyM7** [albertomosconi/foss-apps#40]
### App Name
MoeList

### Category
Entretainment

### Description
Unofficial MAL (MyAnimeList) client. With this app you can easily track, rate, organize and discover new Anime & Manga.

### Links
Source: https://github.com/axiel7/MoeList
Play Store: https://play.google.com/store/apps/details?id=com.axiel7.moelist

**Comment by albertomosconi** [comment]
Hi, thanks for your suggestion, how does this compare to [AnYme](https://github.com/zunjae/AnYme)?

**Comment by RickyM7** [comment]
@albertomosconi I think it does not have much comparison, because anYme is an mal account manager and an anime player, while MoeList is mostly an MAL account manager. However, on the part of the MAL account manager, anYme can manage the anime part, while MoeList can manage the anime part and the manga part of the MAL account, and it does so in a simple and efficient way, which is perfect for those who seek only to manage their MAL account, furthermore MoeList is at the beginning of development and this means that it can still improve a lot.

**Comment by albertomosconi** [comment]
I see, I think I will add them both, thank you for your feedback 😁
