### ISSUE TITLE
Photok

### ISSUE THREAD

**Issue by comparesheriff** [albertomosconi/foss-apps#42]
### app name
Photok

### category
Privacy and Security, Multimedia

### description
Photok encrypts your photos locally on your device and keeps them safe from others.

### links
Source : [https://github.com/leonlatsch/photok](https://github.com/leonlatsch/photok)
F-Droid: [https://f-droid.org/packages/dev.leonlatsch.photok/](https://f-droid.org/packages/dev.leonlatsch.photok/)

**Comment by albertomosconi** [comment]
Thanks!
