### ISSUE TITLE
Incorrect listing - Anyme App not open source

### ISSUE THREAD

**Issue by coderkei** [albertomosconi/foss-apps#55]
### app name
Anyme

### category
Anime

### description
You have listed Anyme, however this app is not open source. The github page is simply used as a front for downloading the app. The app is proprietary. A screenshot is linked.

![](https://i.ibb.co/sw3XfN3/Screenshot-2021-09-05-17-03-39-46-3aea4af51f236e4932235fdada7d1643.jpg)

### links
[https://github.com/zunjae/AnYme](https://github.com/zunjae/AnYme)

**Comment by albertomosconi** [comment]
thank you, I had completely missed that.
