### ISSUE TITLE
Add PCAPdroid

### ISSUE THREAD

**Issue by emanuele-f** [albertomosconi/foss-apps#59]
### app name
PCAPdroid

### category
Security and Privacy

### description
An Android app which lets you monitor and export the network traffic of your device without root. Traffic can be dumped in the PCAP format to be analyzed with popular tools like Wireshark, even in real time. The built-in traffic monitor lets you detect suspicious connections made by user and system apps.

### links
Source: https://github.com/emanuele-f/PCAPdroid
F-Droid: https://f-droid.org/packages/com.emanuelef.remote_capture
Google Play: https://play.google.com/store/apps/details?id=com.emanuelef.remote_capture

**Comment by albertomosconi** [comment]
Awesome app!
I feel like this fits better in a "System Info" category, along with apps like BetterBatteryStats and CPU Info, what do you think?

**Comment by emanuele-f** [comment]
I would agree if PCAPdroid was a simple network monitor showing download and upload traffic volume with a chart, but this is not the case. It is more like a `tcpdump` or a `wireshark` for Android due to its ability to process traffic and extract info (e.g. the HTTP requests). Many users use it to check which connections are made in the background by the apps, for example to detect suspicious uploads of data to a remote server. In my opinion, its features make it more suitable for the "Security and Privacy" category, even though such category currently mainly contains firewalls/OTP apps. In short, it's more similar to `Exodus` than CPU info :)

PS. blocking traffic is currently a work-in-progress, see https://github.com/emanuele-f/PCAPdroid/issues/144

**Comment by albertomosconi** [comment]
You're right, I missed all the extra features. I'll add it now :fire:

**Comment by emanuele-f** [comment]
Great, thanks!
